---
- name: Reboot
  reboot:

- name: Restart multipath
  systemd:
    name: multipathd
    state: restarted

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true
