apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rule-cluster-health.yaml
  - rule-node.yaml
  - rule-workload.yaml
  - rule-storage.yaml
  - rule-cert.yaml
  - rule-rpi.yaml
  - rule-monitoring-agent.yaml
  - rule-envoy-gateway.yaml
