apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm.yaml
  - httproute.yaml
  - externalsecret-alertmanager-oidc.yaml
  - securitypolicy-alertmanager.yaml
  - externalsecret-prometheus-oidc.yaml
  - securitypolicy-prometheus.yaml

configMapGenerator:
  - name: kube-prometheus-stack-helm-values
    files:
      - base-values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
