apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-keycloak
spec:
  endpoints:
    - fqdn:
        hostname: keycloak.keycloak.svc.cluster.local
        port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: prometheus
  oidc:
    provider:
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-keycloak
          port: 80
      issuer: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform"
      authorizationEndpoint: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform/protocol/openid-connect/auth"
      tokenEndpoint: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform/protocol/openid-connect/token"
    clientID: "${OIDC_CLIENT_ID}"
    clientSecret:
      name: oidc-client-secret
    redirectURL: "https://prometheus.${CLUSTER_INTERNAL_DOMAIN}/oauth2/callback"
    logoutPath: "/oauth2/logout"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: alertmanager-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: alertmanager
  oidc:
    provider:
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: backend-keycloak
          port: 80
      issuer: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform"
      authorizationEndpoint: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform/protocol/openid-connect/auth"
      tokenEndpoint: "https://keycloak.${CLUSTER_INTERNAL_DOMAIN}/realms/platform/protocol/openid-connect/token"
    clientID: "${OIDC_CLIENT_ID}"
    clientSecret:
      name: oidc-client-secret
    redirectURL: "https://alertmanager.${CLUSTER_INTERNAL_DOMAIN}/oauth2/callback"
    logoutPath: "/oauth2/logout"
