apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-cloudflare

configMapGenerator:
  - name: external-dns-monitoring-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
