apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: grafana-oidc
        property: client_secret
