---
services:
  op-connect-api:
    image: 1password/connect-api:latest@sha256:e915c0c843972f02b0e7e2de502bda8bd4a092288b3f1866098a857bd715a281
    hostname: ${ENV}-op-connect-api
    ports:
      - "8080:8080"
    environment:
      OP_SESSION: ${OP_SESSION}
    volumes:
      - op-data:/home/opuser/.op/data

  op-connect-sync:
    image: 1password/connect-sync:latest@sha256:6297ca6136c0f0fb096bc64c49e1bc8df2aab35282ebff8c7bb60745ef176d0d
    hostname: ${ENV}-op-connect-sync
    environment:
      OP_SESSION: ${OP_SESSION}
    volumes:
      - op-data:/home/opuser/.op/data

  ansible-runner:
    build:
      context: ./docker
    hostname: ${ENV}-ansible-runner
    environment:
      SSH_AUTH_SOCK: /ssh-agent.sock
      OP_CONNECT_TOKEN: ${OP_CONNECT_TOKEN}
      OP_CONNECT_HOST: http://${ENV}-op-connect-api:8080
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent.sock
      - ./docker/ssh/config:/root/.ssh/config:ro
      - ./docker/ssh/keys:/root/.ssh/keys:ro
      - ./provisioner:/ansible
      - ./manifests:/manifests:ro
      - ./.secret/${ENV}:/.secret
      - ./.kube/${ENV}:/root/.kube
    tty: true

volumes:
  op-data:
