[tools]
uv = "0.11.7"
packer = "1.15.1"
flux2 = "latest"
k9s = "latest"
helm = "latest"
stern = "latest"
kustomize = "latest"
conftest = "0.62.0"
kubeconform = "0.6.7"
actionlint = "1.7.7"

[env]
KUBECONFIG = ".secret/prod/config"
