apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-backend
  target:
    name: loki-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: access_key_id
      remoteRef:
        key: garage-cluster-credentials
        property: loki_access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: garage-cluster-credentials
        property: loki_secret_access_key
