# cilium helm values (hubble)

# Hubble observability
# https://docs.cilium.io/en/latest/observability/hubble/
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: false
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: false
