---
- name: Get system architecture
  command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Add Fluent Bit APT key
  get_url:
    url: https://packages.fluentbit.io/fluentbit.key
    dest: /usr/share/keyrings/fluentbit-keyring.asc
    mode: "0644"

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false

- name: Add Fluent Bit APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/fluentbit-keyring.asc] https://packages.fluentbit.io/ubuntu/{{ ubuntu_codename.stdout }} {{ ubuntu_codename.stdout }} main"
    filename: fluent-bit
    state: present

- name: Install Fluent Bit
  apt:
    name: fluent-bit
    state: present
    update_cache: true

- name: Copy Fluent Bit configuration
  template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    mode: "0644"
  notify: restart fluent-bit

- name: Copy Fluent Bit parsers
  template:
    src: fluent-bit-parsers.conf.j2
    dest: /etc/fluent-bit/parsers.conf
    mode: "0644"
  notify: restart fluent-bit

- name: Enable and start Fluent Bit
  systemd:
    name: fluent-bit
    state: started
    enabled: true
