apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-backend
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword:8080
      vaults:
        br-cluster-prod: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            namespace: onepassword
            key: token
