apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: zitadel-terraform
spec:
  interval: 5m
  url: https://github.com/bright-room/br-cluster-zitadel-terraform
  ref:
    branch: main
  secretRef:
    name: zitadel-terraform-repo-auth
