apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-nodes
  labels:
    app: external-node-exporter
    kubernetes.io/service-name: external-nodes
addressType: IPv4
endpoints:
  - addresses:
      - 172.22.10.1
    nodeName: br-gateway1
    conditions:
      ready: true
ports:
  - name: metrics
    port: 9100
    protocol: TCP
