apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

configMapGenerator:
  - name: cloudnative-pg-monitoring-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
