---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      interval: 30s
