---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/platform/external-secrets/app/overlays/prod
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-app
    - name: onepassword-connect-app
  path: ./manifests/platform/external-secrets/config/overlays/prod
  prune: true
