# opentelemetry-collector helm values (otlp-http-cors)
config:
  receivers:
    otlp:
      protocols:
        http:
          cors:
            allowed_origins:
              - "http://*.${CLUSTER_DOMAIN}"
              - "https://*.${CLUSTER_DOMAIN}"
