---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

configMapGenerator:
  - name: csi-external-snapshotter-helm-values
    behavior: merge
    files:
      - overlay-values.yaml=values.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: csi-external-snapshotter
    path: helm-patch.yaml
