apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-smtp-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-smtp-creds
  data:
    - secretKey: smtp_host
      remoteRef:
        key: resend
        property: smtp_host
    - secretKey: smtp_port
      remoteRef:
        key: resend
        property: smtp_port
    - secretKey: smtp_user
      remoteRef:
        key: resend
        property: smtp_user
    - secretKey: smtp_password
      remoteRef:
        key: resend
        property: smtp_password
    - secretKey: smtp_from
      remoteRef:
        key: resend
        property: from_address
    - secretKey: smtp_from_name
      remoteRef:
        key: resend
        property: from_name
