apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-secrets
  data:
    - secretKey: masterkey
      remoteRef:
        key: zitadel
        property: masterkey
    - secretKey: db_password
      remoteRef:
        key: zitadel
        property: db_password
    # smtp-password is added in a later PR once Resend is provisioned.
