---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: zitadel-db
  data:
    - secretKey: password
      remoteRef:
        key: postgresql
        property: zitadel_password
