---
# cilium helm values (monitoring)

# Prometheus monitoring for cilium-operator
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    annotations:
      grafana_folder: Cilium

# Prometheus monitoring for cilium-agent
# https://docs.cilium.io/en/latest/observability/metrics/
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "10s"
    relabelings:
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: node
        replacement: $${1}
    trustCRDsExist: true

# Grafana dashboards for cilium-agent
dashboards:
  enabled: true
  annotations:
    grafana_folder: Cilium
