# longhorn helm values (prod overlay)
defaultSettings:
  defaultDataPath: /var/lib/longhorn
defaultBackupStore:
  backupTarget: "s3://k3s-longhorn@ap-northeast-1/"
  backupTargetCredentialSecret: longhorn-backup-secret
