---
- op: add
  path: /spec/valuesFrom/-
  value:
    kind: ConfigMap
    name: external-dns-helm-values
    valuesKey: overlay-values.yaml
- op: add
  path: /spec/valuesFrom/-
  value:
    kind: ConfigMap
    name: external-dns-monitoring-values
    valuesKey: values.yaml
    optional: true
