apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-secret
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak
        property: admin_password
