# tempo helm values (base, grafana/tempo single-binary chart)

tempo:
  reportingEnabled: false
  memBallastSizeMbs: 256

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  storage:
    trace:
      backend: s3
      wal:
        path: /var/tempo/wal
      s3:
        bucket: k3s-tempo
        endpoint: ${CLUSTER_S3_SERVER}:${CLUSTER_S3_PORT}
        region: ap-northeast-1
        forcepathstyle: true
        insecure: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: longhorn

service:
  type: ClusterIP

serviceMonitor:
  enabled: false
