---
- name: Delete old certbot working directories
  file:
    path: "{{ lets_encrypt.virtual_environment }}"
    state: absent

- name: Create certbot working directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0644"
  with_items:
    - "{{ lets_encrypt.virtual_environment }}"
    - "{{ lets_encrypt.virtual_environment }}/logs"
    - "{{ lets_encrypt.virtual_environment }}/config"

- name: Create certbot secret directory
  file:
    path: "{{ lets_encrypt.virtual_environment }}/.secrets"
    state: directory
    mode: "0700"

- name: Install certbot and cloudflare plugin in virtual environment
  pip:
    name: "{{ item }}"
    virtualenv: "{{ lets_encrypt.virtual_environment }}"
    virtualenv_command: "python3 -m venv"
    state: present
  with_items:
    - "certbot=={{ versions.certbot }}"
    - "certbot-dns-cloudflare"

- name: Create Cloudflare secret file
  lineinfile:
    path: "{{ lets_encrypt.virtual_environment }}/.secrets/cloudflare_credentials.ini"
    line: "dns_cloudflare_api_token={{ secret_cloudflare_token }}"
    create: true
    state: present
    owner: root
    group: root
    mode: "0600"

- name: Add SSL certificate update cron
  cron:
    name: SSL certificate update
    minute: "0"
    hour: "0,12"
    day: "*"
    month: "*"
    weekday: "*"
    job: "python -c 'import random; import time; time.sleep(random.random() * 60)' && {{ lets_encrypt.virtual_environment }}/bin/certbot renew"
    user: "root"
    disabled: false
    state: present
