---
- name: Set operator credentials from cached secrets
  set_fact:
    _garage_access_key: "{{ secret_garage_operators[garage_user_item.name]['access_key_id'] }}"
    _garage_secret_key: "{{ secret_garage_operators[garage_user_item.name]['secret_access_key'] }}"
  no_log: true

- name: Check if key already exists
  command: garage key info {{ _garage_access_key }}
  register: key_check
  changed_when: false
  failed_when: false
  environment:
    GARAGE_CONFIG_FILE: "{{ garage.config_dir }}/garage.toml"

- name: Import key if not exists
  command: >
    garage key import
    --yes -n {{ garage_user_item.name }}
    {{ _garage_access_key }} {{ _garage_secret_key }}
  when: key_check.rc != 0
  no_log: true
  environment:
    GARAGE_CONFIG_FILE: "{{ garage.config_dir }}/garage.toml"

- name: Grant bucket access to key
  command: >
    garage bucket allow
    --read --write --owner
    {{ garage_user_item.bucket_acl.bucket_name }}
    --key {{ _garage_access_key }}
  register: bucket_allow
  changed_when: '"updated" in bucket_allow.stdout'
  failed_when: false
  environment:
    GARAGE_CONFIG_FILE: "{{ garage.config_dir }}/garage.toml"
