---
- name: Pre-configuration
  include_tasks: pre_configuration.yaml
  tags: [system]

- name: DHCP configuration
  include_tasks: dhcp.yaml
  tags: [dhcp]

- name: DNS configuration
  include_tasks: dns.yaml
  tags: [dns]

- name: NTP configuration
  include_tasks: ntp.yaml
  tags: [ntp]

- name: Cloudflared (br-infra Tunnel) configuration
  include_tasks: cloudflared.yaml
  tags: [cloudflared]
