apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-proxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - internal-envoy-proxy.yaml
  - internal-gateway-class.yaml
  - internal-gateway.yaml
