- op: add
  path: /spec/valuesFrom/-
  value:
    kind: ConfigMap
    name: opentelemetry-collector-helm-values
    valuesKey: overlay-values.yaml
- op: add
  path: /spec/valuesFrom/-
  value:
    kind: ConfigMap
    name: opentelemetry-collector-monitoring-values
    valuesKey: values.yaml
    optional: true
