---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-substitution-externalsecret
  namespace: flux-system
spec:
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: cert-manager-substitution
  data:
  - secretKey: ACME_EMAIL
    remoteRef:
      key: cert-bot
      property: mail_address
