apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-externalsecret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
  data:
  - secretKey: api-token
    remoteRef:
      key: cert-bot
      property: cloudflare_api_token
