---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oidc
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-oidc
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: tf-zitadel-output
        property: longhorn_client_id
    - secretKey: client_secret
      remoteRef:
        key: tf-zitadel-output
        property: longhorn_client_secret
