apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-client
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: oidc-client-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: envoy-gateway-oidc
        property: client_secret
