apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alloy-events

resources:
  - ../../base

configMapGenerator:
  - name: alloy-events-helm-values
    behavior: merge
    files:
      - overlay-values.yaml=values.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: alloy-events
    path: helm-patch.yaml
