---
- name: Fetch Garage RPC secret
  run_once: true
  when: secrets_garage_rpc_secret is not defined
  become: false
  block:
    - name: Get Garage RPC secret
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "garage"
        section: "rpc"
        field: "secret"
      register: _secrets_garage_rpc_secret_raw
      no_log: true
      delegate_to: localhost

    - name: Cache Garage RPC secret
      set_fact:
        secrets_garage_rpc_secret: "{{ _secrets_garage_rpc_secret_raw.field.value }}"
        cacheable: true
      no_log: true
