---
- name: Fetch cloudflare API token
  run_once: true
  when: secrets_cloudflare_token is not defined
  become: false
  block:
    - name: Get cloudflare token
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "cert-bot"
        field: "cloudflare_api_token"
      register: _secrets_cloudflare_token_raw
      no_log: true
      delegate_to: localhost

    - name: Cache cloudflare token
      set_fact:
        secrets_cloudflare_token: "{{ _secrets_cloudflare_token_raw.field.value }}"
        cacheable: true
      no_log: true
