---
- name: Fetch k3s cluster token
  block:
    - name: Get k3s token
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "k3s"
        field: "token"
      register: _k3s_token_raw
      no_log: true
      delegate_to: localhost

    - name: Cache k3s token
      set_fact:
        secret_k3s_token: "{{ _k3s_token_raw.field.value }}"
        cacheable: true
      no_log: true
  run_once: true
  when: secret_k3s_token is not defined
  become: false
