---
- name: Fetch cloudflared br-infra tunnel credentials
  run_once: true
  when: secrets_cloudflared_br_infra is not defined
  become: false
  block:
    - name: Get br-infra account_tag
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "cloudflared"
        field: "br_infra_account_tag"
      register: _secrets_cloudflared_br_infra_account_tag_raw
      no_log: true
      delegate_to: localhost

    - name: Get br-infra tunnel_id
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "cloudflared"
        field: "br_infra_tunnel_id"
      register: _secrets_cloudflared_br_infra_tunnel_id_raw
      no_log: true
      delegate_to: localhost

    - name: Get br-infra tunnel_secret
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "cloudflared"
        field: "br_infra_tunnel_secret"
      register: _secrets_cloudflared_br_infra_tunnel_secret_raw
      no_log: true
      delegate_to: localhost

    - name: Cache cloudflared br-infra credentials
      set_fact:
        secrets_cloudflared_br_infra:
          account_tag: "{{ _secrets_cloudflared_br_infra_account_tag_raw.field.value }}"
          tunnel_id: "{{ _secrets_cloudflared_br_infra_tunnel_id_raw.field.value }}"
          tunnel_secret: "{{ _secrets_cloudflared_br_infra_tunnel_secret_raw.field.value }}"
        cacheable: true
      no_log: true
