---
- name: Fetch Discord webhook (cluster maintenance)
  run_once: true
  when: secrets_discord_webhook is not defined
  become: false
  block:
    - name: Get Discord webhook URL
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "discord-webhook-cluster-maintenance"
        field: "webhook_url"
      register: _secrets_discord_webhook_raw
      no_log: true
      delegate_to: localhost

    - name: Cache Discord webhook URL
      set_fact:
        secrets_discord_webhook: "{{ _secrets_discord_webhook_raw.field.value }}"
        cacheable: true
      no_log: true
