---
- name: Fetch garage operator credentials
  run_once: true
  when:
    - secrets_garage_operators is not defined
    - garage.provisioning.users is defined
  become: false
  block:
    - name: Get operator credentials from 1Password
      # field label は section 名をプレフィクスに含めて item 全体で unique
      # にする (external-secrets の onepassword-connect provider が label
      # フラット検索しかサポートしないため)。
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "garage"
        section: "{{ item.0.name }}"
        field: "{{ item.0.name }}_{{ item.1 }}"
      register: _secrets_garage_operators_raw
      loop: "{{ garage.provisioning.users | product(['access_key_id', 'secret_access_key']) | list }}"
      no_log: true
      delegate_to: localhost

    - name: Cache garage operator credentials
      set_fact:
        secrets_garage_operators: >-
          {%- set ns = namespace(d={}) -%}
          {%- for user in garage.provisioning.users -%}
            {%- set ns.d = ns.d | combine({
              user.name: {
                'access_key_id': _secrets_garage_operators_raw.results[loop.index0 * 2].field.value,
                'secret_access_key': _secrets_garage_operators_raw.results[loop.index0 * 2 + 1].field.value
              }
            }) -%}
          {%- endfor -%}
          {{ ns.d }}
        cacheable: true
      no_log: true
