---
- name: Fetch GitHub App credentials
  block:
    - name: Get GitHub App ID
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "flux-system"
        field: "app_id"
      register: _github_app_id_raw
      no_log: true
      delegate_to: localhost

    - name: Get GitHub App Installation ID
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "flux-system"
        field: "installation_id"
      register: _github_app_installation_id_raw
      no_log: true
      delegate_to: localhost

    - name: Get GitHub App Private Key
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "flux-system"
        field: "private_key"
      register: _github_app_private_key_raw
      no_log: true
      delegate_to: localhost

    - name: Cache GitHub App credentials
      set_fact:
        secret_github_app_id: "{{ _github_app_id_raw.field.value }}"
        secret_github_app_installation_id: "{{ _github_app_installation_id_raw.field.value }}"
        secret_github_app_private_key: "{{ _github_app_private_key_raw.field.value }}"
        cacheable: true
      no_log: true
  run_once: true
  when: secret_github_app_id is not defined
  become: false
