---
- name: Fetch admin email address
  block:
    - name: Get admin email
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "cert-bot"
        field: "mail_address"
      register: _admin_email_raw
      no_log: true
      delegate_to: localhost

    - name: Cache admin email
      set_fact:
        secret_admin_email: "{{ _admin_email_raw.field.value }}"
        cacheable: true
      no_log: true
  run_once: true
  when: secret_admin_email is not defined
  become: false
