---
- name: Fetch restic credentials
  run_once: true
  when: secrets_restic_password is not defined
  become: false
  block:
    - name: Get restic password
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "restic"
        field: "password"
      register: _secrets_restic_password_raw
      no_log: true
      delegate_to: localhost

    - name: Get restic S3 access key
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "garage"
        section: "restic"
        field: "access_key_id"
      register: _secrets_restic_s3_access_key_raw
      no_log: true
      delegate_to: localhost

    - name: Get restic S3 secret key
      onepassword.connect.field_info:
        vault: "{{ vault_id }}"
        item: "garage"
        section: "restic"
        field: "secret_access_key"
      register: _secrets_restic_s3_secret_key_raw
      no_log: true
      delegate_to: localhost

    - name: Cache restic credentials
      set_fact:
        secrets_restic_password: "{{ _secrets_restic_password_raw.field.value }}"
        secrets_restic_s3_access_key: "{{ _secrets_restic_s3_access_key_raw.field.value }}"
        secrets_restic_s3_secret_key: "{{ _secrets_restic_s3_secret_key_raw.field.value }}"
        cacheable: true
      no_log: true
