---
- name: Fetch garage RPC secret
  include_tasks: fetch_garage_rpc_secret.yaml
  when: "'garage_rpc_secret' in required_secrets"

- name: Fetch k3s token
  include_tasks: fetch_k3s_token.yaml
  when: "'k3s_token' in required_secrets"

- name: Fetch cloudflare token
  include_tasks: fetch_cloudflare_token.yaml
  when: "'cloudflare_token' in required_secrets"

- name: Fetch admin email
  include_tasks: fetch_admin_email.yaml
  when: "'admin_email' in required_secrets"

- name: Fetch restic credentials
  include_tasks: fetch_restic.yaml
  when: "'restic' in required_secrets"

- name: Fetch GitHub App credentials
  include_tasks: fetch_github_app.yaml
  when: "'github_app' in required_secrets"

- name: Fetch garage operator credentials
  include_tasks: fetch_garage_operators.yaml
  when: "'garage_operators' in required_secrets"

- name: Fetch 1Password Connect credentials
  include_tasks: fetch_onepassword_connect.yaml
  when: "'onepassword_connect' in required_secrets"
