---
- name: Restart kea-dhcp4
  systemd:
    name: kea-dhcp4-server
    state: restarted

- name: Restart coredns
  systemd:
    name: coredns
    state: restarted

- name: Restart ntp
  service:
    name: chrony
    state: restarted

- name: Restart cloudflared
  service:
    name: cloudflared
    state: restarted
