---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - externalsecret-discord.yaml
  - eventsource-workflow.yaml
  - workflowtemplate-discord.yaml
  - sensor-discord.yaml
