---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: "b8m.app"
  CLUSTER_INTERNAL_DOMAIN: "cluster-internal.bright-room.net"
  KUBE_VIP_ADDRESS: "172.22.10.60"
  CLUSTER_GATEWAY_IP: "172.22.10.70"
  INTERNAL_CLUSTER_GATEWAY_IP: "172.22.10.71"
  COREDNS_ETCD_URL: "http://172.22.10.1:2379"
  TRUSTED_INTERNAL_POD_CIDR: "10.42.0.0/16"
  CLOUDFLARED_TUNNEL_ID: "a033f223-65e3-4bb5-aa55-d258e1c368b5"
  CLOUDFLARED_TUNNEL_CNAME: "a033f223-65e3-4bb5-aa55-d258e1c368b5.cfargotunnel.com"
