---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy-cp-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: alloy-cp
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: loki-app
  path: ./manifests/platform/alloy-cp/app/overlays/prod
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy-cp-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: alloy-cp
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: alloy-cp-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/alloy-cp/monitoring/overlays/prod
  prune: true
