---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: argo-workflows
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
  path: ./manifests/platform/argo-workflows/app/overlays/prod
  prune: true
  wait: true
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows-config
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: argo-workflows-app
    - name: envoy-gateway-config
  path: ./manifests/platform/argo-workflows/config/overlays/prod
  prune: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows-samples
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: argo-workflows
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: argo-workflows-app
  path: ./manifests/platform/argo-workflows/samples/overlays/prod
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows-notify
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: argo-workflows
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: argo-workflows-app
    - name: external-secrets-config
  path: ./manifests/platform/argo-workflows/notify/overlays/prod
  prune: true
  timeout: 5m
