---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/platform/envoy-gateway/app/overlays/prod
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway-app
    - name: cert-manager-config
  path: ./manifests/platform/envoy-gateway/config/overlays/prod
  prune: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/envoy-gateway/monitoring/overlays/prod
  prune: true
