apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-coredns-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: external-dns-coredns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/platform/external-dns-coredns/app/overlays/prod
  prune: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
