---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluent-common
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: fluent
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/platform/fluent/common/overlays/prod
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentd-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: fluent
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluent-common
    - name: external-secrets-config
    - name: cert-manager-config
    - name: loki-app
  path: ./manifests/platform/fluent/fluentd/overlays/prod
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentd-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: fluent
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluentd-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/fluent/fluentd/monitoring/overlays/prod
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluent-bit-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: fluent
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluent-common
    - name: external-secrets-config
    - name: fluentd-app
  path: ./manifests/platform/fluent/fluent-bit/overlays/prod
  prune: true
  wait: true
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluent-bit-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: fluent
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: fluent-bit-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/fluent/fluent-bit/monitoring/overlays/prod
  prune: true
