---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-app
    - name: external-secrets-config
  path: ./manifests/platform/grafana/app/overlays/prod
  prune: true
  wait: true
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-config
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: grafana-app
    - name: envoy-gateway-config
  path: ./manifests/platform/grafana/config/overlays/prod
  prune: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: grafana-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/grafana/monitoring/overlays/prod
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-dashboards
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: grafana
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: grafana-app
  path: ./manifests/platform/grafana/dashboards/overlays/prod
  prune: true
  wait: true
  timeout: 5m
