apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy-app.yaml
  - cert-manager-app.yaml
  - cilium-app.yaml
  - coredns-app.yaml
  - csi-external-snapshotter-app.yaml
  - envoy-gateway-app.yaml
  - external-dns-app.yaml
  - external-secrets-app.yaml
  - flux-app.yaml
  - garage-app.yaml
  - kube-prometheus-stack-app.yaml
  - kube-vip-app.yaml
  - loki-app.yaml
  - longhorn-app.yaml
  - metrics-server-app.yaml
  - onepassword-connect-app.yaml
  - tempo-app.yaml
