---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector-app
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: otel
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-config
    - name: kube-prometheus-stack-app
    - name: loki-app
    - name: tempo-app
  path: ./manifests/platform/opentelemetry-collector/app/overlays/prod
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector-monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: otel
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: opentelemetry-collector-app
    - name: kube-prometheus-stack-app
  path: ./manifests/platform/opentelemetry-collector/monitoring/overlays/prod
  prune: true
