---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - externalsecret-argo-workflows.yaml
  - cluster.yaml
  - database-argo-workflows.yaml
