apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-backend
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
        AWS_ENDPOINTS: "https://backup-storage.cluster-internal.bright-room.net:3900"
  data:
    - secretKey: access_key_id
      remoteRef:
        key: garage
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: garage
        property: secret_access_key
