---
versions:
  k3s: "v1.35.3+k3s1"
  kubectl: "v1.35.0"
  helm: "v4.0.0"
  garage: "v2.2.0"
  restic: "0.18.1"
  etcd: "v3.6.0"
  coredns: "1.14.2"
  certbot: "5.4.0"
  node_exporter: "1.11.0"
  alloy: "1.15.1"
