---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-coredns

resources:
  - ../../base

configMapGenerator:
  - name: external-dns-coredns-helm-values
    behavior: merge
    files:
      - overlay-values.yaml=values.yaml

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: external-dns-coredns
    path: helm-patch.yaml
