---
- name: Get system architecture
  command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Download restic binary
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ versions.restic }}/restic_{{ versions.restic }}_linux_{{ system_arch.stdout }}.bz2"
    dest: "{{ tmp_dir }}/restic_{{ versions.restic }}_linux_{{ system_arch.stdout }}.bz2"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Extract restic binary
  shell: "bzip2 -dc {{ tmp_dir }}/restic_{{ versions.restic }}_linux_{{ system_arch.stdout }}.bz2 > {{ restic.binary_path }}"

- name: Set restic binary permissions
  file:
    path: "{{ restic.binary_path }}"
    owner: "root"
    group: "root"
    mode: "0755"
