apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak-config
  namespace: flux-system
spec:
  interval: 5m
  provider: github
  url: https://github.com/bright-room/br-cluster-keycloak-terraform.git
  ref:
    branch: main
  secretRef:
    name: flux-system
