# kube-vip helm values (base)
config:
  address: "${KUBE_VIP_ADDRESS}"

env:
  cp_enable: "true"
  svc_enable: "false"
  vip_arp: "true"
  vip_leaderelection: "true"
  vip_leaseduration: "15"
  vip_renewdeadline: "10"
  vip_retryperiod: "2"
  cp_namespace: "kube-system"
  lb_port: "6443"
  prometheus_server: ":2112"

envValueFrom:
  vip_nodename:
    fieldRef:
      fieldPath: spec.nodeName

serviceAccount:
  create: true
  name: kube-vip

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
