---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-cloudflare-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: externaldns-cloudflare-token
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflare-externaldns
        property: api_token
