apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fluentd-tls
spec:
  secretName: fluentd-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: fluentd.fluent.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - fluentd.fluent.svc.cluster.local
    - fluentd.fluent.svc
    - fluentd
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
