apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluentd-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-backend
  target:
    name: fluentd-secrets
    creationPolicy: Owner
  data:
    - secretKey: fluentd-shared-key
      remoteRef:
        key: fluent-credentials
        property: shared-key
