---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-main-config
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
data:
  fluent.conf: |-
    @include config.d/*.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-extra-files
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
data:
  01_sources.conf: |-
    ## Sources
    ##
    ## logs from fluent-bit forwarders
    <source>
        @type forward
        @label @FORWARD
        bind "#{ENV['FLUENTD_FORWARD_BIND'] || '0.0.0.0'}"
        port "#{ENV['FLUENTD_FORWARD_PORT'] || '24224'}"
        <transport tls>
            cert_path /etc/fluent/certs/tls.crt
            private_key_path /etc/fluent/certs/tls.key
        </transport>
        <security>
        self_hostname "#{ENV['FLUENTD_FORWARD_SEC_SELFHOSTNAME'] || 'fluentd-aggregator'}"
        shared_key "#{ENV['FLUENT_AGGREGATOR_SHARED_KEY'] || 'sharedkey'}"
        </security>
    </source>
    ## Enable Prometheus endpoint
    <source>
        @type prometheus
        @id in_prometheus
        bind "0.0.0.0"
        port 24231
        metrics_path "/metrics"
    </source>
    <source>
        @type prometheus_monitor
        @id in_prometheus_monitor
    </source>
    <source>
        @type prometheus_output_monitor
        @id in_prometheus_output_monitor
    </source>
    ## Enable syslog endpoint (for external hosts)
    <source>
        @type syslog
        @label @FORWARD
        tag host
        bind 0.0.0.0
        port 5140
        protocol_type udp
        <parse>
            message_format rfc3164
        </parse>
    </source>

  02_filters.conf: |-
    ##
    ## Filters
    ##
    <label @FORWARD>
        # Re-route fluentd logs (discard)
        <match kube.var.log.containers.fluentd**>
            @type relabel
            @label @FLUENT_LOG
        </match>
        <match **>
            @type relabel
            @label @DISPATCH
        </match>
    </label>

  03_dispatch.conf: |-
    # Discard FLUENTD LOGS
    <label @FLUENT_LOG>
      <match **>
        @type null
        @id ignore_fluent_logs
      </match>
    </label>
    # Dispatch logs to Loki
    <label @DISPATCH>
        # Calculate prometheus metrics
        <filter **>
            @type prometheus
            <metric>
                name fluentd_input_status_num_records_total
                type counter
                desc The total number of incoming records
                <labels>
                tag ${tag}
                hostname ${host}
                </labels>
            </metric>
        </filter>
        <match **>
            @type relabel
            @label @OUTPUT_LOKI
        </match>
    </label>

  04_output.conf: |-
    #
    # Output: Loki
    #
    <label @OUTPUT_LOKI>
        <match **>
            @type loki
            @id out_loki
            @log_level info
            url "#{ENV['LOKI_URL']}"
            extra_labels {"job": "fluentd"}
            line_format json
            <label>
                app
                container
                pod
                namespace
                host
                filename
            </label>
            <buffer>
                flush_thread_count 8
                flush_interval 5s
                chunk_limit_size 2M
                queue_limit_length 32
                retry_max_interval 30
                retry_forever true
            </buffer>
        </match>
    </label>
