# fluentd helm values (base)

image:
  repository: "ricsanfre/fluentd-aggregator"
  pullPolicy: "IfNotPresent"
  tag: "v1.18-debian-1"

kind: "Deployment"
replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
rbac:
  create: false

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

mountVarLogDirectory: false
mountDockerContainersDirectory: false

env:
  - name: FLUENT_AGGREGATOR_SHARED_KEY
    valueFrom:
      secretKeyRef:
        name: fluentd-secrets
        key: fluentd-shared-key
  - name: LOKI_URL
    value: "http://loki-gateway.loki"

mainConfigMapNameOverride: fluentd-main-config
extraFilesConfigMapNameOverride: fluentd-extra-files

configMapConfigs: []

volumes:
  - name: fluentd-tls
    secret:
      secretName: fluentd-tls

volumeMounts:
  - mountPath: /etc/fluent/certs
    name: fluentd-tls
    readOnly: true

service:
  type: "ClusterIP"
  annotations: {}
  ports:
    - name: forwarder
      protocol: TCP
      containerPort: 24224

plugins: []
