apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-br-cluster-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-backend
    kind: ClusterSecretStore
  target:
    name: cloudflared-br-cluster-tunnel-credentials
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {"AccountTag":"{{ .account_tag }}","TunnelSecret":"{{ .tunnel_secret }}","TunnelID":"{{ .tunnel_id }}"}
  data:
    - secretKey: account_tag
      remoteRef:
        key: cloudflared
        property: br_cluster_account_tag
    - secretKey: tunnel_secret
      remoteRef:
        key: cloudflared
        property: br_cluster_tunnel_secret
    - secretKey: tunnel_id
      remoteRef:
        key: cloudflared
        property: br_cluster_tunnel_id
