apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-backend
  target:
    name: garage-rpc-secret
    creationPolicy: Owner
  data:
    - secretKey: rpcSecret
      remoteRef:
        key: garage-cluster-credentials
        property: rpc_secret
