---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
spec:
  interval: 1h
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    tag: v2.2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 30m
  chart:
    spec:
      chart: ./script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: garage-helm-values
      valuesKey: base-values.yaml
