apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-provisioning-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-backend
  target:
    name: garage-provisioning-secret
    creationPolicy: Owner
  data:
    - secretKey: loki_access_key_id
      remoteRef:
        key: garage-cluster-credentials
        property: loki_access_key_id
    - secretKey: loki_secret_access_key
      remoteRef:
        key: garage-cluster-credentials
        property: loki_secret_access_key
    - secretKey: tempo_access_key_id
      remoteRef:
        key: garage-cluster-credentials
        property: tempo_access_key_id
    - secretKey: tempo_secret_access_key
      remoteRef:
        key: garage-cluster-credentials
        property: tempo_secret_access_key
    - secretKey: longhorn_access_key_id
      remoteRef:
        key: garage-cluster-credentials
        property: longhorn_access_key_id
    - secretKey: longhorn_secret_access_key
      remoteRef:
        key: garage-cluster-credentials
        property: longhorn_secret_access_key
